import { Inter } from 'next/font/google';
import './globals.css';
import { Lato } from 'next/font/google';
import Footer from '../components/Footer';
import { LetterSpacingProvider } from '@/components/hooks/useLetterSpacing';

const inter = Inter({ subsets: ['latin'] });
const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.variable}`}>
        <LetterSpacingProvider>
          {children}

          <Footer />
        </LetterSpacingProvider>
      </body>
    </html>
  );
}
